Replaced crappy functions for compiling CS, CEL, and CEGUI, added to disable xerces parser. Renamed some functions for consistancy.

diff --git a/scripts/ptbuild/buildscript b/scripts/ptbuild/buildscript
--- a/scripts/ptbuild/buildscript
+++ b/scripts/ptbuild/buildscript
@@ -17,9 +17,7 @@ CEGUI_DN='CEGUI-0.6.1'
 
 
 
-function install_dir_choose {
-
-	exit_var=0
+function INSTALL_DIR_CHOOSE {
 
 	RET=`zenity --list --radiolist --width=480 --height=100 \
 		--title "PTBuild version $version" \
@@ -29,21 +27,21 @@ function install_dir_choose {
 
 	if echo "$RET" | grep $"Default"; then
 
-		install_dir=/opt
-		psdir=$install_dir/peragro_svn/peragro
+		INSTALL_DIR=/opt
+		ptir=$INSTALL_DIR/peragro_svn/peragro
 		exit_var=1
 
 	fi
 	if echo "$RET" | grep $"Custom"; then
 
-		install_dir=$(zenity --file-selection --directory)
-		psdir=$install_dir/peragro_svn/peragro
+		INSTALL_DIR=$(zenity --file-selection --directory)
+		ptdir=$INSTALL_DIR/peragro_svn/peragro
 		exit_var=1
 
 	fi
 
 }
-function choose_optimize {
+function CHOOSE_OPTIMIZATION {
 	# Asks user to select their processor
 	RET=`zenity --list --radiolist --width=700 --height=285 \
 		--title "PTBuild version $version" \
@@ -70,22 +68,11 @@ function choose_optimize {
 
 	fi
 }
-function build_env {
-
-        PASS_TRIES=3
-        # sudo -k to test script
-        sudo -k
-        for (( i=1; i<=$PASS_TRIES; i++ )); do
-              zenity --entry --title "Password Prompt" --hide-text --text $"Enter your password (try #$i of $PASS_TRIES)." | sudo -S -v
-              # exit loop if password was correct
-              [ "$?" -eq "0" ] && break
-        done
-        # "i" greater than $PASS_TRIES means $PASS_TRIES failed tries
-        [ "$i" -gt "$PASS_TRIES" ] && { zenity --error --text "Failed to enter correct password, exiting..."; exit 1; }
-        [ -d $install_dir/peragro_svn ] || sudo mkdir $install_dir/peragro_svn
-        sudo chmod -R a+rw $install_dir
-        touch $install_dir/peragro_svn/ptbuild.log
-        cd $install_dir/peragro_svn
+function BUILD_ENV {
+	sudo mkdir $INSTALL_DIR/peragro_svn
+	sudo chmod -R a+rw $INSTALL_DIR
+	touch $INSTALL_DIR/peragro_svn/ptbuild.log
+	cd $INSTALL_DIR/peragro_svn
 
 }
 function GET_CS_SOURCE {
@@ -138,93 +125,33 @@ function GET_CEGUI_SOURCE {
 		rm $CEGUI_FN
 
 }
-
-function buildcal3d {
-
-
-	zenity --progress --pulsate --text $"Compiling Cal3d....please wait..." &
-	ZENITY_PID="$!"
-
-	# Modifies Makefile.am
-	sed -i 's/all_libraries = @all_libraries@/#all_libraries = @all_libraries@/' $ptdir/cal3d/src/cal3d/Makefile.am
-
-
-	cd $ptdir/cal3d
-
-	echo " " >> $install_dir/peragro_svn/ptbuild.log 2>&1
-	echo " " >> $install_dir/peragro_svn/ptbuild.log 2>&1
-	echo "------------------------------------------------" >> $install_dir/peragro_svn/ptbuild.log 2>&1
-	echo "|                                              |" >> $install_dir/peragro_svn/ptbuild.log 2>&1
-	echo "|            BUILD LOG FOR CAL3D               |" >> $install_dir/peragro_svn/ptbuild.log 2>&1
-	echo "|                                              |" >> $install_dir/peragro_svn/ptbuild.log 2>&1
-	echo "------------------------------------------------" >> $install_dir/peragro_svn/ptbuild.log 2>&1
-	echo " " >> $install_dir/peragro_svn/ptbuild.log 2>&1
-	echo " " >> $install_dir/peragro_svn/ptbuild.log 2>&1
-
-	./autogen.sh >> $install_dir/peragro_svn/ptbuild.log 2>&1
-
-	$cal3dconfig >> $install_dir/peragro_svn/ptbuild.log 2>&1
-
-	make >> $install_dir/peragro_svn/ptbuild.log 2>&1
-
-	make install >> $install_dir/peragro_svn/ptbuild.log 2>&1
-
-	kill $ZENITY_PID
-
+function COMPILE_CEL {
+	echo "Compiling CEL"
+	cd $INSTALL_DIR/CEL_latest
+	./autogen.sh
+	./configure
+	jam -aq libs plugins cel-config
 }
-function buildcs {
-
-
-	zenity --progress --pulsate --text $"Compiling CrystalSpace...you may want to take a nap or grab some tea...." &
-	ZENITY_PID="$!"
-
-	cd $ptdir/cs
-
-	echo " " >> $install_dir/peragro_svn/ptbuild.log 2>&1
-	echo " " >> $install_dir/peragro_svn/ptbuild.log 2>&1
-	echo "------------------------------------------------" >> $install_dir/peragro_svn/ptbuild.log 2>&1
-	echo "|                                              |" >> $install_dir/peragro_svn/ptbuild.log 2>&1
-	echo "|             BUILD LOG FOR CS                 |" >> $install_dir/peragro_svn/ptbuild.log 2>&1
-	echo "|                                              |" >> $install_dir/peragro_svn/ptbuild.log 2>&1
-	echo "------------------------------------------------" >> $install_dir/peragro_svn/ptbuild.log 2>&1
-	echo " " >> $install_dir/peragro_svn/ptbuild.log 2>&1
-	echo " " >> $install_dir/peragro_svn/ptbuild.log 2>&1
-
-	$csconfig >> $install_dir/peragro_svn/ptbuild.log 2>&1
-	jam -aq libs plugins cs-config walktest >> $install_dir/peragro_svn/ptbuild.log 2>&1
-
-	kill $ZENITY_PID
-
+function COMPILE_CS {
+	cd $INSTALL_DIR/CS_latest
+	echo "Compiling CrystalSpace"
+	./configure --without-java --without-lib3ds --without-libaws --with-CEGUI=$CEGUI
+	jam -aq libs plugins cs-config walktest basemapgen lighter2
 }
-function buildcel {
-
-	zenity --progress --pulsate --text $"Compiling CEL...please wait...." &
-	ZENITY_PID="$!"
-
-	cd $ptdir/cel 
-	
-	echo " " >> $install_dir/peragro_svn/ptbuild.log 2>&1
-	echo " " >> $install_dir/peragro_svn/ptbuild.log 2>&1
-	echo "------------------------------------------------" >> $install_dir/peragro_svn/ptbuild.log 2>&1
-	echo "|                                              |" >> $install_dir/peragro_svn/ptbuild.log 2>&1
-	echo "|             BUILD LOG FOR CEL                |" >> $install_dir/peragro_svn/ptbuild.log 2>&1
-	echo "|                                              |" >> $install_dir/peragro_svn/ptbuild.log 2>&1
-	echo "------------------------------------------------" >> $install_dir/peragro_svn/ptbuild.log 2>&1
-	echo " " >> $install_dir/peragro_svn/ptbuild.log 2>&1
-	echo " " >> $install_dir/peragro_svn/ptbuild.log 2>&1
-
-	./autogen.sh  >> $install_dir/peragro_svn/ptbuild.log 2>&1
-	$celconfig >> $install_dir/peragro_svn/ptbuild.log 2>&1
-	jam -aq  >> $install_dir/peragro_svn/ptbuild.log 2>&1
-
-	kill $ZENITY_PID
-
+function COMPILE_CEGUI {
+	cd $INSTALL_DIR
+	tar -xf $CEGUI_FN
+	cd $INSTALL_DIR/$CEGUI_DN
+	echo "Compiling CEGUI"
+	./configure --prefix=$CEGUI --disable-xerces-c
+	make
+	make install
 }
-function resolveKarmic {
+function RESOLVE_KARMIC {
 
 	# attempt to resolve dependencies
 	(
-        echo "10" ; sleep 3 && dpkg_check
+        echo "10" ; sleep 3 && DPKG_CHECK
         echo "# Updating Sources Cache"
         echo "35" ; sudo apt-get update
         echo "# Installing Software"
@@ -237,7 +164,7 @@ function resolveKarmic {
           --text="Checking if any package managers are running" \
           --percentage=0
 }
-function dpkg_check {
+function DPKG_CHECK {
 
 	# Makes sure package manager isn't running.
 	if ps -U root -u root u | grep "synaptic" | grep -v grep;
@@ -259,27 +186,17 @@ fi
 
 
 }
-function ask {
+function ASK {
 
 	# Asks user if they want to attempt to resolve dependancies.
 	zenity --question --text $"Would you like to attempt to get all software needed to compile Peragro? (Only necessary if this is the first time you have run this script.) "
 	if [ $? -eq 0 ] ; then
-		resolveKarmic
+		RESOLVE_KARMIC
 	fi
 
 
 }
-function artAsk {
-
-	# Asks user if they want to backup their art directory.
-	zenity --question --text $"Would you like to try to backup your art directory? Hit cancel if this is the first time you have run this script."
-	if [ $? -eq 0 ] ; then
-	artBackup
-	fi
-
-
-}
-function buildSources {
+function BUILD_SOURCES {
 		
 		# Runs functions that build source code.
 		buildcal3d
@@ -294,13 +211,24 @@ function buildSources {
 		killall zenity
 
 }
+function PASSWORD {
+sudo -k
+	for (( i=1; i<=$PASS_TRIES; i++ )); do
+		zenity --entry --title "Password Prompt" --hide-text --text $"Enter your password (try #$i of $PASS_TRIES)." | 		sudo -S -v
+
+# exit loop if password was correct
+	[ "$?" -eq "0" ] && break
+	done
+	# "i" greater than $PASS_TRIES means $PASS_TRIES failed tries
+	[ "$i" -gt "$PASS_TRIES" ] && { zenity --error --text "Failed to enter correct password, exiting..."; exit 1; }
+}
 
 
 
-install_dir_choose
+INSTALL_DIR_CHOOSE
 # setup_profile
-build_env
-ask
-choose_optimization
+BUILD_ENV
+ASK
+CHOOSE_OPTIMIZATION
 
 exit 0
